/* Banques de questions. Convention : a[0] est TOUJOURS la bonne réponse (les choix sont mélangés à l'affichage). */
window.ADM = window.ADM || {};

ADM.PASSAGES = {
  brebeuf: {
    title: 'Texte : Les ratons laveurs du mont Royal',
    text: `<p>Chaque automne, les ratons laveurs du mont Royal se préparent pour l'hiver. Contrairement à ce que beaucoup de gens croient, ils n'hibernent pas vraiment : ils dorment beaucoup, mais se réveillent lors des journées plus douces. Pour survivre au froid, ils accumulent des réserves de graisse. C'est pourquoi on les voit souvent fouiller les poubelles des pique-niqueurs en octobre.</p>
           <p>Les gardes-parc demandent pourtant aux visiteurs de ne jamais les nourrir. En effet, un raton habitué à la nourriture humaine perd sa méfiance et peut devenir agressif. De plus, les croustilles et les frites sont mauvaises pour sa santé. « Un raton sauvage est un raton en santé », répète souvent une garde-parc.</p>`,
  },
  roberval: {
    title: 'Texte : Un seul hiver',
    text: `<p>En 1541, le roi de France nomme Jean-François de La Rocque de Roberval lieutenant général de la Nouvelle-France. Sa mission : fonder une colonie et trouver des richesses. L'année suivante, il traverse l'océan avec des colons et s'installe près de l'endroit où se trouve aujourd'hui la ville de Québec.</p>
           <p>L'hiver est terrible. Le froid et le scorbut, une maladie causée par le manque de vitamine C, font de nombreuses victimes. Au printemps 1543, découragé, Roberval rentre en France. Sa colonie n'aura duré qu'un seul hiver. Il faudra attendre plus de soixante ans avant que Samuel de Champlain fonde Québec, en 1608.</p>`,
  },
};

ADM.Q = {
  brebeuf_math: [
    { cat: 'logique', q: 'Quel nombre complète la suite?', v: '2 · 6 · 12 · 20 · 30 · ?', a: ['42', '40', '36', '44'], why: 'On ajoute 4, 6, 8, 10… puis 12.' },
    { cat: 'math', q: 'Un sac de 6 bagels coûte 9 $. Combien coûtent 10 bagels au même prix?', a: ['15 $', '12 $', '18 $', '13,50 $'], why: 'Un bagel coûte 1,50 $, et 10 × 1,50 $ = 15 $.' },
    { cat: 'math', q: 'Combien font 3/4 + 1/8?', a: ['7/8', '4/12', '1', '5/8'], why: '3/4 = 6/8, et 6/8 + 1/8 = 7/8.' },
    { cat: 'math', q: 'Le périmètre d\'un carré est de 36 cm. Quelle est son aire?', a: ['81 cm²', '36 cm²', '72 cm²', '144 cm²'], why: 'Chaque côté mesure 9 cm, et 9 × 9 = 81.' },
    { cat: 'logique', q: 'Tous les Blorks sont des Zims. Certains Zims sont bleus. Que peut-on conclure?', a: ['On ne peut pas savoir si un Blork est bleu', 'Tous les Blorks sont bleus', 'Aucun Blork n\'est bleu', 'Tous les Zims sont des Blorks'], why: 'Les Zims bleus ne sont peut-être pas des Blorks.' },
    { cat: 'math', q: 'Un autobus part à 8 h 45 et roule pendant 2 h 30. À quelle heure arrive-t-il?', a: ['11 h 15', '10 h 75', '11 h 45', '10 h 15'], why: '8 h 45 + 2 h = 10 h 45, puis + 30 min = 11 h 15.' },
    { cat: 'logique', q: 'Quelle lettre continue la suite?', v: 'A · C · F · J · ?', a: ['O', 'N', 'M', 'P'], why: 'On avance de 2, 3, 4, puis 5 lettres : J + 5 = O.' },
    { cat: 'math', q: 'Combien font 25 % de 80?', a: ['20', '25', '40', '16'], why: '25 %, c\'est le quart : 80 ÷ 4 = 20.' },
    { cat: 'logique', q: 'Léa est plus grande que Sami. Sami est plus grand que Noé. Qui est le plus petit?', a: ['Noé', 'Sami', 'Léa', 'On ne peut pas savoir'] },
  ],
  brebeuf_lecture: [
    { cat: 'lecture', q: 'Selon le texte, que font les ratons laveurs l\'hiver?', a: ['Ils dorment beaucoup, mais se réveillent quand il fait plus doux', 'Ils hibernent sans jamais se réveiller', 'Ils migrent vers le sud', 'Ils vivent dans les maisons'] },
    { cat: 'lecture', q: 'Pourquoi ne faut-il pas nourrir les ratons?', a: ['Ils perdent leur méfiance et peuvent devenir agressifs', 'Ils deviennent trop gros pour grimper', 'Ils arrêtent de dormir', 'C\'est interdit seulement l\'été'] },
    { cat: 'lecture', q: 'Dans le texte, le mot « méfiance » veut dire…', a: ['le fait de rester sur ses gardes', 'la faim', 'la gentillesse', 'la fatigue'] },
  ],
  brebeuf_gram: [
    { cat: 'fr', q: 'Quelle phrase est bien écrite?', a: ['Les pommes que j\'ai mangées étaient délicieuses.', 'Les pommes que j\'ai mangé étaient délicieuses.', 'Les pommes que j\'ai mangés étaient délicieuses.', 'Les pommes que j\'ai manger étaient délicieuses.'], why: 'Avec « avoir », on accorde avec le complément placé AVANT : « que » = les pommes.' },
    { cat: 'fr', q: 'Quel est le pluriel de « un chou »?', a: ['des choux', 'des chous', 'des choues', 'des chouxs'], why: 'Bijou, caillou, chou, genou, hibou, joujou, pou : ils prennent un X!' },
    { cat: 'fr', q: 'Complète : « Il faut que tu ___ tes devoirs. »', a: ['fasses', 'fais', 'feras', 'faisais'], why: 'Après « il faut que », on met le subjonctif : que tu fasses.' },
    { cat: 'fr', q: 'Complète : « Les élèves ___ préparé leurs crayons. »', a: ['ont', 'on', 'onts', 'sont'], why: '« Ont », c\'est le verbe avoir (ils ont). « On » est un pronom.' },
    { cat: 'fr', q: 'Quel est le synonyme de « perspicace »?', a: ['clairvoyant', 'paresseux', 'bavard', 'timide'] },
    { cat: 'fr', q: 'Quelle phrase contient une erreur d\'accord?', a: ['Les filles sont parti tôt.', 'Les garçons sont partis tôt.', 'Elles sont parties tôt.', 'Nous sommes partis tôt.'], why: 'Avec « être », le participe s\'accorde avec le sujet : les filles sont parties.' },
    { cat: 'fr', q: 'Complète : « Hier, mon frère ___ allé au parc. »', a: ['est', 'a', 'et', 'ait'], why: 'Le verbe aller se conjugue avec « être » au passé composé.' },
    { cat: 'fr', q: 'Quel mot se prononce comme « verre »?', a: ['vert', 'vare', 'verra', 'veau'], why: 'Verre, vert, ver, vers et vair : cinq homophones!' },
  ],
  je_fr: [
    { cat: 'fr', q: 'Complète : « Il ___ trois bagels ce matin. »', a: ['a mangé', 'à mangé', 'a manger', 'as mangé'], why: '« A » sans accent, c\'est le verbe avoir (il a).' },
    { cat: 'fr', q: 'Quel est le féminin de « acteur »?', a: ['actrice', 'acteuse', 'acteure', 'acteresse'] },
    { cat: 'fr', q: 'Complète : « Demain, nous ___ au cinéma. »', a: ['irons', 'irrons', 'allerons', 'iront'], why: 'Futur du verbe aller : nous irons (un seul R).' },
    { cat: 'fr', q: 'Quel mot est mal orthographié?', a: ['bibliotèque', 'dictionnaire', 'mathématiques', 'enveloppe'], why: 'On écrit « bibliothèque », avec un H.' },
    { cat: 'fr', q: 'Complète : « Les chanteuses se sont ___ avant le spectacle. »', a: ['maquillées', 'maquillés', 'maquillé', 'maquiller'], why: 'Ici, on accorde avec le sujet « les chanteuses ».' },
    { cat: 'fr', q: 'Quel est le contraire de « généreux »?', a: ['avare', 'gentil', 'riche', 'heureux'] },
    { cat: 'fr', q: 'Quelle phrase est au futur simple?', a: ['Je danserai ce soir.', 'Je dansais ce soir.', 'Je danserais ce soir.', 'Je vais danser ce soir.'], why: '« Je vais danser », c\'est le futur proche. Le futur simple : je danserai.' },
  ],
  cdm_logic: [
    { cat: 'logique', q: 'Si hier était dimanche, quel jour serons-nous après-demain?', a: ['Mercredi', 'Mardi', 'Jeudi', 'Lundi'], why: 'Aujourd\'hui, c\'est lundi. Après-demain : mercredi.' },
    { cat: 'logique', q: 'Quel nombre complète la suite?', v: '1 · 1 · 2 · 3 · 5 · 8 · ?', a: ['13', '11', '12', '16'], why: 'Chaque nombre est la somme des deux précédents : 5 + 8 = 13.' },
    { cat: 'logique', q: 'Émile, Louis et David portent chacun un chandail rouge, bleu ou vert. Émile ne porte pas de rouge. David porte du vert. Quelle couleur porte Louis?', a: ['Rouge', 'Bleu', 'Vert', 'On ne peut pas savoir'], why: 'David = vert. Émile ne porte pas de rouge, donc bleu. Il reste le rouge pour Louis.' },
    { cat: 'logique', q: 'Pomme est à pommier ce que raisin est à…', a: ['vigne', 'vin', 'grappe', 'fruit'] },
    { cat: 'logique', q: 'Combien de carrés en tout vois-tu dans une grille de 2 cases sur 2?', a: ['5', '4', '6', '8'], why: '4 petits carrés + le grand carré qui les entoure = 5.' },
    { cat: 'logique', q: 'Un escargot grimpe un mur de 5 m. Le jour, il monte de 3 m; la nuit, il glisse de 2 m. En combien de jours atteint-il le sommet?', a: ['3 jours', '5 jours', '4 jours', '2 jours'], why: 'Après 2 jours et 2 nuits, il est à 2 m. Le 3e jour, il monte de 3 m : sommet!' },
  ],
  rob_fr: [
    { cat: 'lecture', q: 'Pourquoi le roi envoie-t-il Roberval en Nouvelle-France?', a: ['Pour fonder une colonie et trouver des richesses', 'Pour faire la guerre à l\'Angleterre', 'Pour ouvrir une école', 'Pour chasser le castor seulement'] },
    { cat: 'lecture', q: 'Selon le texte, qu\'est-ce que le scorbut?', a: ['Une maladie causée par le manque de vitamine C', 'Un bateau', 'Une tempête de neige', 'Un fort en bois'] },
    { cat: 'lecture', q: 'Combien de temps la colonie de Roberval a-t-elle duré?', a: ['Un seul hiver', 'Soixante ans', 'Dix ans', 'Elle existe encore'] },
    { cat: 'lecture', q: 'Dans le texte, « découragé » veut dire…', a: ['qui a perdu espoir', 'très fâché', 'très fatigué', 'très riche'] },
  ],
  rob_math: [
    { cat: 'math', q: 'Une classe de 28 élèves forme des équipes de 4. Combien y a-t-il d\'équipes?', a: ['7', '6', '8', '112'] },
    { cat: 'math', q: 'Combien font 0,5 + 0,25?', a: ['0,75', '0,30', '0,7', '1,25'] },
    { cat: 'math', q: 'Un rectangle mesure 8 cm sur 5 cm. Quelle est son aire?', a: ['40 cm²', '26 cm²', '13 cm²', '45 cm²'] },
    { cat: 'math', q: 'Quel nombre est le plus grand?', a: ['0,9', '0,45', '0,099', '0,89'], why: '0,9 = 0,90, qui est plus grand que 0,89.' },
    { cat: 'math', q: 'Sophie a 3 fois plus de cartes que Karim. Ensemble, ils en ont 48. Combien Karim en a-t-il?', a: ['12', '16', '36', '24'], why: 'Karim = 1 part, Sophie = 3 parts. 4 parts = 48, donc 1 part = 12.' },
    { cat: 'math', q: 'Quelle fraction est égale à 1/2?', a: ['4/8', '2/6', '3/5', '5/8'] },
  ],
  rob_logic: [
    { cat: 'logique', q: 'Qu\'est-ce qui continue la suite?', v: '🔺 🔵 🔺 🔵 🔺 ❓', a: ['🔵', '🔺', '🟩', '⭐'] },
    { cat: 'logique', q: 'Qu\'est-ce qui continue la suite?', v: '⬆️ ➡️ ⬇️ ⬅️ ⬆️ ❓', a: ['➡️', '⬇️', '⬅️', '⬆️'], why: 'La flèche tourne d\'un quart de tour vers la droite à chaque fois.' },
    { cat: 'logique', q: 'Qu\'est-ce qui continue la suite?', v: '🟥 🟥 🟦 🟥 🟥 🟦 🟥 ❓', a: ['🟥', '🟦', '🟩', '🟨'], why: 'Le motif rouge-rouge-bleu se répète.' },
    { cat: 'logique', q: 'Lequel est l\'intrus?', v: '🍎 🍌 🍇 🥕 🍓', a: ['🥕', '🍌', '🍇', '🍓'], why: 'La carotte est un légume. Les autres sont des fruits.' },
    { cat: 'logique', q: 'Qu\'est-ce qui continue la suite?', v: '⭐ · ⭐⭐ · ⭐⭐⭐ · ❓', a: ['⭐⭐⭐⭐', '⭐⭐', '⭐', '⭐⭐⭐⭐⭐'] },
    { cat: 'logique', q: 'Qu\'est-ce qui continue la suite?', v: '🌑 🌓 🌕 🌗 🌑 ❓', a: ['🌓', '🌕', '🌗', '🌑'], why: 'Les phases de la Lune reviennent toujours dans le même ordre.' },
  ],
  msl: [
    { s: 'Français', q: 'Le pluriel de « cheval » est « chevals ».', v: false, why: 'des chevaux' },
    { s: 'Français', q: '« Rapidement » est un adverbe.', v: true },
    { s: 'Français', q: 'Le mot « oiseau » contient les voyelles a, e, i, o et u.', v: true },
    { s: 'Français', q: '« Ils » est un déterminant.', v: false, why: 'c\'est un pronom' },
    { s: 'Français', q: 'Le féminin de « chanteur » est « chanteuse ».', v: true },
    { s: 'Français', q: 'On écrit « des cônes oranges ».', v: false, why: 'orange, comme couleur, est invariable' },
    { s: 'Mathématique', q: '7 × 8 = 56', v: true },
    { s: 'Mathématique', q: '0,5 est plus grand que 0,45.', v: true },
    { s: 'Mathématique', q: 'Un triangle a 4 côtés.', v: false, why: 'il en a 3' },
    { s: 'Mathématique', q: '1/4 est plus grand que 1/2.', v: false, why: 'c\'est le contraire' },
    { s: 'Mathématique', q: '12 est un nombre premier.', v: false, why: '12 = 3 × 4' },
    { s: 'Mathématique', q: '9 × 6 = 56', v: false, why: '9 × 6 = 54' },
    { s: 'Sciences', q: 'L\'eau gèle à 0 °C.', v: true },
    { s: 'Sciences', q: 'Les araignées sont des insectes.', v: false, why: 'ce sont des arachnides, avec 8 pattes' },
    { s: 'Sciences', q: 'Les plantes ont besoin de lumière pour faire la photosynthèse.', v: true },
    { s: 'Sciences', q: 'Le son voyage plus vite que la lumière.', v: false, why: 'la lumière est beaucoup plus rapide' },
    { s: 'Sciences', q: 'La Terre tourne autour du Soleil.', v: true },
    { s: 'Sciences', q: 'La Lune produit sa propre lumière.', v: false, why: 'elle reflète celle du Soleil' },
    { s: 'Univers social', q: 'Montréal a été fondée en 1642.', v: true },
    { s: 'Univers social', q: 'La capitale du Canada est Toronto.', v: false, why: 'c\'est Ottawa' },
    { s: 'Univers social', q: 'Jacques Cartier a visité Hochelaga en 1535.', v: true },
    { s: 'Univers social', q: 'La capitale du Québec est Montréal.', v: false, why: 'c\'est la ville de Québec' },
    { s: 'Univers social', q: 'Samuel de Champlain a fondé Québec en 1608.', v: true },
    { s: 'Univers social', q: 'Le fleuve qui passe à Montréal s\'appelle le Mississippi.', v: false, why: 'c\'est le Saint-Laurent' },
    { s: 'Anglais', q: '« Apple » veut dire « pomme ».', v: true },
    { s: 'Anglais', q: 'En anglais, « library » veut dire « librairie ».', v: false, why: 'ça veut dire bibliothèque' },
    { s: 'Anglais', q: '« Yesterday » veut dire « demain ».', v: false, why: 'ça veut dire hier' },
    { s: 'Anglais', q: 'Le pluriel de « child » est « childs ».', v: false, why: 'c\'est children' },
    { s: 'Anglais', q: '« I am » vient du verbe « to be ».', v: true },
    { s: 'Anglais', q: '« Blue » est une couleur.', v: true },
  ],
};

// Convention dictée : o[0] est la bonne orthographe; r = la règle affichée en cas de faute.
ADM.DICTEE = {
  cdm: {
    title: 'Dictée : « Un matin rue Sherbrooke »',
    parts: [
      'Ce matin-là, les cônes orange que j\'ai ',
      { o: ['vus', 'vu', 'vues'], r: 'Avec « avoir », on accorde avec le complément placé AVANT : « que » = les cônes (masculin pluriel), donc « vus ».' },
      ' sur la rue Sherbrooke s\'étaient encore ',
      { o: ['multipliés', 'multiplié', 'multipliées'], r: 'Verbe pronominal : on accorde avec le sujet « les cônes », donc « multipliés ».' },
      ' pendant la nuit. Mes parents, ',
      { o: ['inquiets', 'inquiet', 'inquiètes'], r: 'L\'adjectif s\'accorde avec « mes parents » (masculin pluriel), donc « inquiets ».' },
      ', cherchaient un chemin vers le collège. Devant moi se dressaient les vieilles tours de pierre, ',
      { o: ['bâties', 'bâtis', 'bâtie'], r: '« Bâties » s\'accorde avec « les tours » (féminin pluriel).' },
      ' il y a plus de trois cents ans. « ',
      { o: ['Quelle', 'Quel', 'Qu\'elle'], r: '« Quelle » s\'accorde avec « journée » (féminin singulier). « Qu\'elle », c\'est « que + elle ».' },
      ' belle journée pour une dictée! » s\'est ',
      { o: ['exclamé', 'exclamée', 'exclamés'], r: 'Le sujet est « le surveillant » (masculin singulier), donc « exclamé ».' },
      ' le surveillant. Les élèves se sont ',
      { o: ['assis', 'assit', 'assient'], r: 'Participe passé du verbe « s\'asseoir » : « assis », accordé avec « les élèves ».' },
      ' en silence. J\'avais ',
      { o: ['acheté', 'achetée', 'achetés'], r: 'Avec « avoir », le complément « un muffin » est placé APRÈS : pas d\'accord, donc « acheté ».' },
      ' un muffin, mais je l\'avais ',
      { o: ['mangé', 'mangée', 'manger'], r: '« L\' » remplace « le muffin » (masculin singulier) et il est placé avant, donc « mangé ».' },
      ' trop vite. ',
      { o: ['Quand', 'Quant', 'Qu\'en'], r: '« Quand » indique le moment. « Quant à » veut dire « en ce qui concerne ».' },
      ' la cloche a sonné, la dictée a commencé. Enfin, presque.',
    ],
  },
};
